version: '3'
services:
  backend:
    container_name: backend
#    image: 678253091836.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-production:latest 
    restart: always
    ports:
      - 8000:8000
    networks:
      - filemaker
    volumes:
      - /opt/logs/backend:/home/filemaker/log
      - /opt/workstation/frontend/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - LOG_PATH=/var/log/backend/backend.log
    env_file:
      - /opt/workstation/backend/backend-code/.env

  celery:
    container_name: celery
#    image: 678253091836.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    image: backend-production:latest 
#    command: celery -A file_maker_system worker --concurrency=2 --prefetch-multiplier=2 --max-memory-per-child=1000000  --loglevel=INFO --logfile=/var/log/celery/celery.log
    command: celery -A file_maker_system worker --concurrency=2 --prefetch-multiplier=1 --max-memory-per-child=500000  --loglevel=INFO --logfile=/var/log/celery/celery.log
    depends_on:
      - backend
    restart: always
    volumes:
      - /opt/logs/celery:/var/log/celery
    env_file:
      - /opt/workstation/backend/backend-code/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


  redis:
    container_name: "redis"
    image: redis:latest
    networks:
      - filemaker
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - /opt/logs/redis:/var/log/redis
    ports:
      - 6379:6379
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
#    image: 678253091836.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    image: frontend-production:latest
    ports:
      - 80:80
    restart: always
    networks:
      - filemaker
    volumes:
      - /opt/logs/frontend:/var/log/frontend
      - /opt/workstation/frontend/nginx.conf:/etc/nginx/nginx.conf      
    environment:
      - LOG_PATH=/var/log/frontend/frontend.log

networks:
  filemaker: {}
